[16기 홍연우] Add: models.py 작성
wecode-bootcamp-korea/16-2nd-bearbnb-backend pull request #1
Opened 2021-01-26 10:18 UTC by redsaumon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 초기 세팅 commit도 rebase해서 models.py commit 하나만 남게 해야하나요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-26 11:54 UTC, lordmyshepherd requested changes

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +    image_url = models.URLField(max_length=2000)
queryset을 다룰 때, 가독성을 위해서 아래와 같이 수정해주세요~
`Image.image_url` vs `image.url`
```suggestion
    url = models.URLField(max_length=2000)
```

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +class Detail(models.Model):
`Space`와 `Detail`의 관계가 One-To-Many 관계가 맞나요?
하나의 숙소에 여러개의 Detail이 존재하나요?

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +        db_table = 'bed_types'
`싱글` / `더블` / `퀸` / `소파베드` 와 같은 데이터를 관리하는 테이블로 잘 만들어 주셨습니다.

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +        db_table = 'bedrooms'
`침실` 데이터를 관리하는 테이블로 잘 만들어 주셨습니다.
`1 번 침실` \ `2 번 침실` \  `공용 공간` 과 같은 데이터가 저장되기 때문에, 숫자를 가지고 있는 것이 아니라 `1 번 침실` \ `2 번 침실` \  `공용 공간` 데이터를 저장할 수 있는 name field가 필요합니다.
```suggestion
class Bedroom(models.Model):
    name    = models.CharField()
    space   = models.ForeignKey('spaces.Space', on_delete=models.CASCADE)

    class Meta:
        db_table = 'bedrooms'
```

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +        db_table = 'bedroom_beds'
아래와 같이 데이터가 테이블에 저장되도록 잘 만들어 주셨습니다.
bedroom = `1 번 침실` 
bed_type = `더블 침대` 
quantity = `2개`

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +        db_table = 'bedrooms'
추가로, 침실의 개수는 space를 참조하고 있는 bedroom의 개수를 count하면 되기 때문에 bedroom의 개수를 의미하는 필드를 만들 필요가 없습니다.

2021-01-26 11:54 UTC, lordmyshepherd commented on spaces/models.py
> +    image_url     = models.URLField(max_length=2000)
아래와 같이 좀 더 필드의 목적을 잘 나타내도록 수정하면 좋을 것 같습니다.
```suggestion
    cleanliness_score   = models.IntegerField(default=0)
    communication_score = models.IntegerField(default=0)
    check_in_score      = models.IntegerField(default=0)
```

2021-01-26 12:09 UTC, redsaumon commented on spaces/models.py
> +    image_url = models.URLField(max_length=2000)
네!!

2021-01-26 12:10 UTC, redsaumon commented on spaces/models.py
> +class Detail(models.Model):
1:1 관계입니다!

2021-01-26 12:11 UTC, redsaumon commented on spaces/models.py
> +        db_table = 'bedrooms'
넵!! 수정하겠습니다~

2021-01-26 12:11 UTC, redsaumon commented on spaces/models.py
> +    image_url     = models.URLField(max_length=2000)
네!!!

2021-01-27 02:09 UTC, lordmyshepherd requested changes

2021-01-27 02:09 UTC, lordmyshepherd commented on spaces/models.py
> +
빈 줄은 지워주세요~

2021-01-27 02:09 UTC, lordmyshepherd commented on spaces/models.py
> +    name    = models.CharField()
migration 된건가요?
`CharField()에 max_length` 속성은 필수로 알고 있었는데, 확인해주실 수 있나요?

2021-01-27 02:09 UTC, lordmyshepherd commented on spaces/models.py
> +class Detail(models.Model):
그렇다면 이정도 데이터는 space table에 합치는게 좋을 것 같습니다!

2021-01-27 02:16 UTC, redsaumon commented on spaces/models.py
> +
네~~~

2021-01-27 02:17 UTC, redsaumon commented on spaces/models.py
> +    name    = models.CharField()
엇 수정하겠습니다!!!

2021-01-27 02:28 UTC, lordmyshepherd commented
LGTM 👍
rebase 💯

2021-01-27 02:28 UTC, merged