[16기 홍연우] Add: signup 생성
wecode-bootcamp-korea/16-2nd-bearbnb-backend pull request #3
Opened 2021-01-29 07:24 UTC by redsaumon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-30 12:55 UTC, ulfrid requested changes
확인 바랍니다~!

2021-01-30 12:55 UTC, ulfrid commented on users/tests.py
> +        response = self.client.post('/users/signup', data=form)
이대로 보내면 실제로 S3에 파일이 작성될것 같은데, 테스트를 작성할때는 실제에 반영되면 안됩니다. 
이때를 위해 fake를 위한 가짜 접속을 구현하는데, mocking, patching이라고 합니다. 
boto3 클라이언트를 모킹하기위한 예제를 찾아서 링크 공유 드립니다. 한번 확인 해주세요.
https://stackoverflow.com/questions/57065702/how-to-properly-patch-boto3-calls-in-unit-test

2021-01-30 12:55 UTC, ulfrid commented on users/views.py
> +            regex           = re.compile(email_reg)
```suggestion
            email_validator       = re.compile(r"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")
```
하나로 줄이면 될 것 같네요

2021-01-31 00:15 UTC, redsaumon commented on users/tests.py
> +        response = self.client.post('/users/signup', data=form)
지훈님 반갑습니다!!!! 읽어보고 수정해보겠습니다!!

2021-01-31 00:16 UTC, redsaumon commented on users/views.py
> +            regex           = re.compile(email_reg)
넵!! 수정하겠습니다!!

2021-01-31 07:26 UTC, ulfrid commented
LGTM👍

2021-01-31 07:26 UTC, merged