[16기 윤정민] Add : listview, unittest 작성
wecode-bootcamp-korea/16-2nd-bearbnb-backend pull request #6
Opened 2021-02-02 08:28 UTC by jeongmin14

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 공간 리스트 뷰, 유닛테스트 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-02-03 01:39 UTC, lordmyshepherd requested changes

2021-02-03 01:39 UTC, lordmyshepherd commented on spaces/tests.py
> +        print(Space.objects.all())
print문은 지워주세요.

2021-02-03 01:39 UTC, lordmyshepherd commented on spaces/tests.py
> +        #  AssertionError: 200 != 400
주석은 지워주세요~~

2021-02-03 01:39 UTC, lordmyshepherd commented on spaces/urls.py
> +
빈 줄은 지워주세요~

2021-02-03 01:39 UTC, lordmyshepherd commented on spaces/views.py
> +    def get(self, request):
정민님.. 정말 코드 잘 작성해주셨네요 👍

2021-02-03 01:39 UTC, lordmyshepherd commented on spaces/views.py
> +            spaces = spaces.filter(location__city=location)
`spaces = Space.objects.all()`에 `spaces.filter(place_type__name=place_type)`할 때 데이터베이스를 조회하게 됩니다.
또한, `spaces.filter(location__city=location)` 호출할 때도 마찬가지입니다.

그래서 아래와 같이 dictionary를 활용해서, 만들어진 dictionary를 unpacking해서 filter를 만들어보시면 좋을 것 같아요~
```python
filter_set = {}
```

2021-02-03 03:12 UTC, jeongmin14 commented on spaces/views.py
> +            spaces = spaces.filter(location__city=location)
네 알겠습니다!!!

2021-02-03 03:43 UTC, jeongmin14 commented on spaces/views.py
> +            spaces = spaces.filter(location__city=location)
프론트와 상의한 필터링이 place_type  부분이라 이 부분만 수정하고 location은 삭제했습니다.

2021-02-03 10:15 UTC, lordmyshepherd requested changes

2021-02-03 10:15 UTC, lordmyshepherd commented on spaces/views.py
> +            spaces = Space.objects.filter(place_type__name=request.GET.get("type"))
아래와 같은 방법으로 dictionary를 활용해서 filter를 구현해보세요.
이 방법으로 구현하기 위해서는 `unpacking` 개념을 공부해보시면 좋겠습니다.
```suggestion
        place_type = request.GET.get("type")

        filter_set = {}
        if place_type:
            filter_set['play_type__name'] = place_type
        spaces = Space.objects.filter(**filter_set)
```

2021-02-03 11:43 UTC, jeongmin14 commented on spaces/views.py
> +            spaces = Space.objects.filter(place_type__name=request.GET.get("type"))
@lordmyshepherd  프로젝트 끝나면 unpacking  자세히 공부해봐야겠어요,,,!

2021-02-03 11:49 UTC, ulfrid commented
LGTM.

2021-02-03 11:49 UTC, merged

2021-02-04 05:51 UTC, soheon-lee commented on add.py
> +ws = wb.active
정민님 이 친구들은 누구인가요